### ISSUE TITLE
2.0 版本

### ISSUE THREAD

**Issue by adwerrd** [bsc-s2/storage-dashboard-vue#10]
项目最近一直没有大动，做过其他项目也学习过其他项目框架的实践后，现在回过头来看看有很多地方写的并不完善，刚好借着权限模块重构的契机，准备在一些模块上做一些 “小手术”，具体包括以下几个方面：
- [x] 代码写法不够规范 （ **es6** 写惯了，看不上现在的代码
- [x] 借鉴 react 项目，更多代码相关的 lint ，更严格控制产出格式 #17 
- [x] **store** 部分代码组织形式，及 **getters** 属性的使用不完善 #14 
- [x] 权限模块过度依赖账户角色，过于复杂且不利于维护，经过讨论准备采用 **权限子项** 的方式进行权限管理 #2 
- [x]  账户信息 部分， **login / bridge** 两个页面逻辑重复比较多，考虑代码重构
- [x] 路由部分是否有改进的空间 ？ 嵌套路由是否能用在当前的业务场景下？ 这里还需要看一下
- [x] **request**  部分考虑不够全面，借机整理出一个比较好的 **axios 配置实践**，并应用到其他项目中 #16 
- [x] 错误全局处理，已经做了一部分，需要后端保存 / 错误更好的展示 / 错误告警等功能 #16 
- [x] 修改 webpack & babel & npm control , 适配最新 vue-cli3
- [x] 登陆页代码分离，减少登录用时
- [x] store manager 部分
- [x] 错误上报格式调整
持续补充中…

**Comment by drmingdrmer** [comment]
> 代码写法不够规范 （ es6 写惯了，看不上现在的代码

怎么达到规范呢... 一般是: 通过bb, 通过工具, 通过模块划分. 如果具体到issue的话需要是一个可以实施的方案(否则作为文化建设考虑...), 譬如 将xxx拆分出来可以提高代码复用和独立测试; 譬如 通过xxx工具可以检查出yyy不规范的用法.

**Comment by adwerrd** [comment]
大概也有写， 第一个是用法上的不规范，这部分先整理一个最优实践; 第二个是代码格式上的不规范，会写更多的 lint 来做检测;
